### ISSUE TITLE
Make holobot 's name as optional alternative command prefix

### ISSUE THREAD

**Issue by AdiReich** [rexor12/holobot#324]
### Summary

for example:
holobot weather Sun
(^ assuming holobots name on the server is holobot)

### Why is this needed?

It is not, I just think it might be nice feature

### Checklist

- [X] I have made sure not to add ANY sensitive information (tokens, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it is not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by rexor12** [comment]
Thank you for the idea, but I cannot support this.

It has been decided since the introduction of interactions (initially called "slash commands") that Holo would avoid reading message content, thus avoiding the need to request the associated intent from Discord. Unfortunately, "prefix commands" inevitably require this intent.

As I understand it, people prefer this way of interacting with bots because of how poor the UX is when it comes to interactions currently, such as the UI lagging or sending the invocation as plain text instead of executing it. This is something that Discord needs to improve and should not require workarounds from bot developers.

I can, however, provide a bit of information regarding how it currently works so that your personal UX is improved. Here are some things that many users don't know:
1. You don't have to type the entire command, you can just type the last bit. Let's say there is a command `/admin commands setrule`. Instead of typing all of that, you can type `/setrule` and the matching command will show up in the auto complete popup.
2. `/` is not the only prefix that works for command auto completion. Based on the previous example, you can type `.setrule` or `$setrule` or even `!setrule`.
3. On PC you can use the tabulator key to jump between parameters. You can use Shift+Tab to jump backwards, like in many applications. On phones you don't need this because tapping is faster.
